// Color palettes for all 25 wedding invitation templates
// Each template has 3 selectable palettes

export type ColorPalette = {
  slug: string
  name: string
  primaryHex: string
  primaryLight: string
  primaryDark: string
  bgPage: string
  bgSection1: string
  bgSection2: string
  bgDark: string
  textDark: string
  textMuted: string
  textAccent: string
  borderAccent: string
  gradientFrom: string
  gradientTo: string
  shadowColor: string
  secondaryHex?: string
}

export const templatePalettes: Record<string, ColorPalette[]> = {
  // min-ivory
  "min-ivory": [
    {
      slug: "ivory-classic",
      name: "Classic Ivory",
      primaryHex: "#C9A96E",
      primaryLight: "#FDF6E3",
      primaryDark: "#A07840",
      bgPage: "bg-[#FDFAF4]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FDF6E3]",
      bgDark: "bg-[#3D3530]",
      textDark: "text-[#2C2416]",
      textMuted: "text-[#8C7B6B]",
      textAccent: "text-[#C9A96E]",
      borderAccent: "border-[#E8D9B8]",
      gradientFrom: "#FDF6E3",
      gradientTo: "#F5EDD0",
      shadowColor: "rgba(201,169,110,0.12)"
    },
    {
      slug: "champagne",
      name: "Champagne",
      primaryHex: "#B8976A",
      primaryLight: "#FBF3E2",
      primaryDark: "#8B6B3D",
      bgPage: "bg-[#FEFCF7]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FBF3E2]",
      bgDark: "bg-[#332B22]",
      textDark: "text-[#2A2018]",
      textMuted: "text-[#877060]",
      textAccent: "text-[#B8976A]",
      borderAccent: "border-[#E2D0B0]",
      gradientFrom: "#FBF3E2",
      gradientTo: "#F0E4C8",
      shadowColor: "rgba(184,151,106,0.12)"
    },
    {
      slug: "blush-whisper",
      name: "Blush Whisper",
      primaryHex: "#C4837A",
      primaryLight: "#FDF0EE",
      primaryDark: "#9B5A52",
      bgPage: "bg-[#FEFAFA]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FDF0EE]",
      bgDark: "bg-[#3D2825]",
      textDark: "text-[#2C1E1C]",
      textMuted: "text-[#8C6B68]",
      textAccent: "text-[#C4837A]",
      borderAccent: "border-[#EDD5D2]",
      gradientFrom: "#FDF0EE",
      gradientTo: "#F5E0DC",
      shadowColor: "rgba(196,131,122,0.12)"
    },
  ],
  // min-slate
  "min-slate": [
    {
      slug: "cool-slate",
      name: "Cool Slate",
      primaryHex: "#64748B",
      primaryLight: "#F1F5F9",
      primaryDark: "#334155",
      bgPage: "bg-[#F8FAFC]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F1F5F9]",
      bgDark: "bg-[#1E293B]",
      textDark: "text-[#0F172A]",
      textMuted: "text-[#64748B]",
      textAccent: "text-[#475569]",
      borderAccent: "border-[#CBD5E1]",
      gradientFrom: "#F1F5F9",
      gradientTo: "#E2E8F0",
      shadowColor: "rgba(100,116,139,0.12)"
    },
    {
      slug: "navy-calm",
      name: "Navy Calm",
      primaryHex: "#1E3A5F",
      primaryLight: "#EFF4FB",
      primaryDark: "#0F2040",
      bgPage: "bg-[#F7F9FC]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#EFF4FB]",
      bgDark: "bg-[#0F2040]",
      textDark: "text-[#0D1B2A]",
      textMuted: "text-[#5B7A9D]",
      textAccent: "text-[#1E3A5F]",
      borderAccent: "border-[#BFCFE3]",
      gradientFrom: "#EFF4FB",
      gradientTo: "#DCEAF7",
      shadowColor: "rgba(30,58,95,0.12)"
    },
    {
      slug: "charcoal-soft",
      name: "Charcoal Soft",
      primaryHex: "#374151",
      primaryLight: "#F3F4F6",
      primaryDark: "#1F2937",
      bgPage: "bg-[#F9FAFB]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F3F4F6]",
      bgDark: "bg-[#111827]",
      textDark: "text-[#111827]",
      textMuted: "text-[#6B7280]",
      textAccent: "text-[#374151]",
      borderAccent: "border-[#D1D5DB]",
      gradientFrom: "#F3F4F6",
      gradientTo: "#E5E7EB",
      shadowColor: "rgba(55,65,81,0.12)"
    },
  ],
  // min-sage
  "min-sage": [
    {
      slug: "sage-green",
      name: "Sage Green",
      primaryHex: "#7D9B76",
      primaryLight: "#EFF4EE",
      primaryDark: "#4A6741",
      bgPage: "bg-[#F7FAF6]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#EFF4EE]",
      bgDark: "bg-[#2D3D2A]",
      textDark: "text-[#1C2B1A]",
      textMuted: "text-[#6B826A]",
      textAccent: "text-[#7D9B76]",
      borderAccent: "border-[#C8D9C4]",
      gradientFrom: "#EFF4EE",
      gradientTo: "#DDE9DA",
      shadowColor: "rgba(125,155,118,0.12)"
    },
    {
      slug: "olive-mist",
      name: "Olive Mist",
      primaryHex: "#8B956D",
      primaryLight: "#F2F3EB",
      primaryDark: "#5F6A40",
      bgPage: "bg-[#F8F9F3]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F2F3EB]",
      bgDark: "bg-[#333A24]",
      textDark: "text-[#21260F]",
      textMuted: "text-[#727A56]",
      textAccent: "text-[#8B956D]",
      borderAccent: "border-[#CCCFA8]",
      gradientFrom: "#F2F3EB",
      gradientTo: "#E4E7D6",
      shadowColor: "rgba(139,149,109,0.12)"
    },
    {
      slug: "forest-soft",
      name: "Forest Soft",
      primaryHex: "#4A6741",
      primaryLight: "#E8F0E6",
      primaryDark: "#2D4428",
      bgPage: "bg-[#F4F8F3]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#E8F0E6]",
      bgDark: "bg-[#1C2E19]",
      textDark: "text-[#142210]",
      textMuted: "text-[#587050]",
      textAccent: "text-[#4A6741]",
      borderAccent: "border-[#B8CEAF]",
      gradientFrom: "#E8F0E6",
      gradientTo: "#D4E4D0",
      shadowColor: "rgba(74,103,65,0.12)"
    },
  ],
  // min-noir
  "min-noir": [
    {
      slug: "pure-noir",
      name: "Pure Noir",
      primaryHex: "#1C1C1C",
      primaryLight: "#F5F5F5",
      primaryDark: "#000000",
      bgPage: "bg-white",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F5F5F5]",
      bgDark: "bg-[#1C1C1C]",
      textDark: "text-[#1C1C1C]",
      textMuted: "text-[#6B6B6B]",
      textAccent: "text-[#1C1C1C]",
      borderAccent: "border-[#E0E0E0]",
      gradientFrom: "#F5F5F5",
      gradientTo: "#EBEBEB",
      shadowColor: "rgba(0,0,0,0.10)"
    },
    {
      slug: "warm-graphite",
      name: "Warm Graphite",
      primaryHex: "#2D2D2D",
      primaryLight: "#F6F5F3",
      primaryDark: "#111111",
      bgPage: "bg-[#FEFEFE]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F6F5F3]",
      bgDark: "bg-[#1A1A18]",
      textDark: "text-[#1A1A18]",
      textMuted: "text-[#6E6E6A]",
      textAccent: "text-[#2D2D2D]",
      borderAccent: "border-[#DEDBD7]",
      gradientFrom: "#F6F5F3",
      gradientTo: "#ECEAE6",
      shadowColor: "rgba(45,45,45,0.10)"
    },
    {
      slug: "ink",
      name: "Ink",
      primaryHex: "#111827",
      primaryLight: "#F3F4F6",
      primaryDark: "#030712",
      bgPage: "bg-[#F9FAFB]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F3F4F6]",
      bgDark: "bg-[#030712]",
      textDark: "text-[#030712]",
      textMuted: "text-[#6B7280]",
      textAccent: "text-[#111827]",
      borderAccent: "border-[#D1D5DB]",
      gradientFrom: "#F3F4F6",
      gradientTo: "#E5E7EB",
      shadowColor: "rgba(17,24,39,0.10)"
    },
  ],
  // min-blush
  "min-blush": [
    {
      slug: "blush-rose",
      name: "Blush Rose",
      primaryHex: "#C4837A",
      primaryLight: "#FCF0EE",
      primaryDark: "#9B5A52",
      bgPage: "bg-[#FEF8F7]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FCF0EE]",
      bgDark: "bg-[#3D2825]",
      textDark: "text-[#2C1E1C]",
      textMuted: "text-[#9B7570]",
      textAccent: "text-[#C4837A]",
      borderAccent: "border-[#EDD5D0]",
      gradientFrom: "#FCF0EE",
      gradientTo: "#F5E0DB",
      shadowColor: "rgba(196,131,122,0.12)"
    },
    {
      slug: "dusty-rose",
      name: "Dusty Rose",
      primaryHex: "#B07B78",
      primaryLight: "#FAF0EE",
      primaryDark: "#8B5A57",
      bgPage: "bg-[#FDF6F5]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FAF0EE]",
      bgDark: "bg-[#382424]",
      textDark: "text-[#281A1A]",
      textMuted: "text-[#906B68]",
      textAccent: "text-[#B07B78]",
      borderAccent: "border-[#E5CECA]",
      gradientFrom: "#FAF0EE",
      gradientTo: "#F0E0DC",
      shadowColor: "rgba(176,123,120,0.12)"
    },
    {
      slug: "mauve-dream",
      name: "Mauve Dream",
      primaryHex: "#9B6E8C",
      primaryLight: "#F6EEF4",
      primaryDark: "#6B4060",
      bgPage: "bg-[#FCF7FA]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F6EEF4]",
      bgDark: "bg-[#301825]",
      textDark: "text-[#22101C]",
      textMuted: "text-[#7A5872]",
      textAccent: "text-[#9B6E8C]",
      borderAccent: "border-[#DFC8D8]",
      gradientFrom: "#F6EEF4",
      gradientTo: "#EBD8E7",
      shadowColor: "rgba(155,110,140,0.12)"
    },
  ],
  // flo-rose
  "flo-rose": [
    {
      slug: "blush-rose",
      name: "Blush Rose",
      primaryHex: "#C4837A",
      primaryLight: "#FDF0EE",
      primaryDark: "#9B5A52",
      bgPage: "bg-[#FEF8F7]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FDF0EE]",
      bgDark: "bg-[#3D2825]",
      textDark: "text-[#2C1E1C]",
      textMuted: "text-[#9B7570]",
      textAccent: "text-[#C4837A]",
      borderAccent: "border-[#EDD5D0]",
      gradientFrom: "#FDF0EE",
      gradientTo: "#F5E0DB",
      shadowColor: "rgba(196,131,122,0.15)"
    },
    {
      slug: "coral-bloom",
      name: "Coral Bloom",
      primaryHex: "#D4826A",
      primaryLight: "#FDF2EE",
      primaryDark: "#A85A42",
      bgPage: "bg-[#FEF9F7]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FDF2EE]",
      bgDark: "bg-[#3D2820]",
      textDark: "text-[#2C1C15]",
      textMuted: "text-[#9B7060]",
      textAccent: "text-[#D4826A]",
      borderAccent: "border-[#EDD8CE]",
      gradientFrom: "#FDF2EE",
      gradientTo: "#F5E2D8",
      shadowColor: "rgba(212,130,106,0.15)"
    },
    {
      slug: "burgundy-petal",
      name: "Burgundy Petal",
      primaryHex: "#8B2635",
      primaryLight: "#F9EAEC",
      primaryDark: "#5C1020",
      bgPage: "bg-[#FDF6F7]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F9EAEC]",
      bgDark: "bg-[#2C0D14]",
      textDark: "text-[#1C0810]",
      textMuted: "text-[#8B5560]",
      textAccent: "text-[#8B2635]",
      borderAccent: "border-[#E8C0C5]",
      gradientFrom: "#F9EAEC",
      gradientTo: "#F0D0D5",
      shadowColor: "rgba(139,38,53,0.15)"
    },
  ],
  // flo-peony
  "flo-peony": [
    {
      slug: "soft-pink",
      name: "Soft Pink",
      primaryHex: "#E8A4B8",
      primaryLight: "#FEF0F4",
      primaryDark: "#C47090",
      bgPage: "bg-[#FFF5F8]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FEF0F4]",
      bgDark: "bg-[#3D1F28]",
      textDark: "text-[#2C1520]",
      textMuted: "text-[#9B7080]",
      textAccent: "text-[#C47090]",
      borderAccent: "border-[#F0D0DC]",
      gradientFrom: "#FEF0F4",
      gradientTo: "#F8DCEA",
      shadowColor: "rgba(232,164,184,0.15)"
    },
    {
      slug: "peach-blush",
      name: "Peach Blush",
      primaryHex: "#E8B4A0",
      primaryLight: "#FEF3EE",
      primaryDark: "#C48060",
      bgPage: "bg-[#FFF8F5]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FEF3EE]",
      bgDark: "bg-[#3D2218]",
      textDark: "text-[#2C1810]",
      textMuted: "text-[#9B7868]",
      textAccent: "text-[#C48060]",
      borderAccent: "border-[#F0D8CC]",
      gradientFrom: "#FEF3EE",
      gradientTo: "#F8E4D8",
      shadowColor: "rgba(232,180,160,0.15)"
    },
    {
      slug: "dusty-lilac",
      name: "Dusty Lilac",
      primaryHex: "#B8A4C8",
      primaryLight: "#F6F0FA",
      primaryDark: "#8870A0",
      bgPage: "bg-[#FAF6FD]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F6F0FA]",
      bgDark: "bg-[#2A1F38]",
      textDark: "text-[#1E1528]",
      textMuted: "text-[#806890]",
      textAccent: "text-[#9878B0]",
      borderAccent: "border-[#DCCCEA]",
      gradientFrom: "#F6F0FA",
      gradientTo: "#EADDF5",
      shadowColor: "rgba(184,164,200,0.15)"
    },
  ],
  // flo-jasmine
  "flo-jasmine": [
    {
      slug: "ivory-white",
      name: "Ivory White",
      primaryHex: "#D4C4A0",
      primaryLight: "#FBF8F0",
      primaryDark: "#A89060",
      bgPage: "bg-[#FEFCF6]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FBF8F0]",
      bgDark: "bg-[#3A3020]",
      textDark: "text-[#282010]",
      textMuted: "text-[#8A7A60]",
      textAccent: "text-[#B89A60]",
      borderAccent: "border-[#EDE0C0]",
      gradientFrom: "#FBF8F0",
      gradientTo: "#F5EDD8",
      shadowColor: "rgba(212,196,160,0.15)"
    },
    {
      slug: "warm-cream",
      name: "Warm Cream",
      primaryHex: "#C8B890",
      primaryLight: "#FAF6EC",
      primaryDark: "#9A8860",
      bgPage: "bg-[#FEFBF4]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FAF6EC]",
      bgDark: "bg-[#38301C]",
      textDark: "text-[#261E0C]",
      textMuted: "text-[#887860]",
      textAccent: "text-[#A89060]",
      borderAccent: "border-[#E8D8B0]",
      gradientFrom: "#FAF6EC",
      gradientTo: "#F2EAD5",
      shadowColor: "rgba(200,184,144,0.15)"
    },
    {
      slug: "champagne-gold",
      name: "Champagne Gold",
      primaryHex: "#C9A96E",
      primaryLight: "#FBF5E6",
      primaryDark: "#9A7838",
      bgPage: "bg-[#FEFAF2]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FBF5E6]",
      bgDark: "bg-[#382A10]",
      textDark: "text-[#261C08]",
      textMuted: "text-[#887050]",
      textAccent: "text-[#C9A96E]",
      borderAccent: "border-[#E8D5A0]",
      gradientFrom: "#FBF5E6",
      gradientTo: "#F5EACC",
      shadowColor: "rgba(201,169,110,0.15)"
    },
  ],
  // flo-orchid
  "flo-orchid": [
    {
      slug: "purple-orchid",
      name: "Purple Orchid",
      primaryHex: "#7B4F8C",
      primaryLight: "#F5EEFA",
      primaryDark: "#532068",
      bgPage: "bg-[#FAF5FD]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F5EEFA]",
      bgDark: "bg-[#28103C]",
      textDark: "text-[#1C082C]",
      textMuted: "text-[#7058808]",
      textAccent: "text-[#7B4F8C]",
      borderAccent: "border-[#D8C0E8]",
      gradientFrom: "#F5EEFA",
      gradientTo: "#EADAF5",
      shadowColor: "rgba(123,79,140,0.15)"
    },
    {
      slug: "lavender",
      name: "Lavender",
      primaryHex: "#9B8FCC",
      primaryLight: "#F2F0FA",
      primaryDark: "#6B60A8",
      bgPage: "bg-[#F8F6FD]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F2F0FA]",
      bgDark: "bg-[#221C48]",
      textDark: "text-[#181438]",
      textMuted: "text-[#706898]",
      textAccent: "text-[#8070B8]",
      borderAccent: "border-[#D5CFE8]",
      gradientFrom: "#F2F0FA",
      gradientTo: "#E5E0F5",
      shadowColor: "rgba(155,143,204,0.15)"
    },
    {
      slug: "deep-plum",
      name: "Deep Plum",
      primaryHex: "#5C2D6E",
      primaryLight: "#F3EAF8",
      primaryDark: "#3A1048",
      bgPage: "bg-[#F9F2FD]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F3EAF8]",
      bgDark: "bg-[#1E0830]",
      textDark: "text-[#140520]",
      textMuted: "text-[#6A4878]",
      textAccent: "text-[#6A3A80]",
      borderAccent: "border-[#D8C0E5]",
      gradientFrom: "#F3EAF8",
      gradientTo: "#E8D5F2",
      shadowColor: "rgba(92,45,110,0.15)"
    },
  ],
  // flo-sakura
  "flo-sakura": [
    {
      slug: "sakura-pink",
      name: "Sakura Pink",
      primaryHex: "#E8A4B8",
      primaryLight: "#FEF0F5",
      primaryDark: "#C07090",
      bgPage: "bg-[#FFF5F8]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FEF0F5]",
      bgDark: "bg-[#3D1E28]",
      textDark: "text-[#2C1420]",
      textMuted: "text-[#9B6878]",
      textAccent: "text-[#C47090]",
      borderAccent: "border-[#F0D0DC]",
      gradientFrom: "#FEF0F5",
      gradientTo: "#F8DCEA",
      shadowColor: "rgba(232,164,184,0.15)"
    },
    {
      slug: "warm-red",
      name: "Warm Red",
      primaryHex: "#C4504A",
      primaryLight: "#FDECEA",
      primaryDark: "#9B2820",
      bgPage: "bg-[#FEF6F5]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FDECEA]",
      bgDark: "bg-[#3D1412]",
      textDark: "text-[#2C0E0C]",
      textMuted: "text-[#9B5550]",
      textAccent: "text-[#C4504A]",
      borderAccent: "border-[#EEC8C5]",
      gradientFrom: "#FDECEA",
      gradientTo: "#F8D8D5",
      shadowColor: "rgba(196,80,74,0.15)"
    },
    {
      slug: "terracotta",
      name: "Terracotta",
      primaryHex: "#C4784A",
      primaryLight: "#FDF0E8",
      primaryDark: "#9B5025",
      bgPage: "bg-[#FEF8F3]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FDF0E8]",
      bgDark: "bg-[#3D1E10]",
      textDark: "text-[#2C1408]",
      textMuted: "text-[#9B6848]",
      textAccent: "text-[#C4784A]",
      borderAccent: "border-[#EDD0B8]",
      gradientFrom: "#FDF0E8",
      gradientTo: "#F5E2D0",
      shadowColor: "rgba(196,120,74,0.15)"
    },
  ],
  // nat-forest
  "nat-forest": [
    {
      slug: "deep-green",
      name: "Deep Green",
      primaryHex: "#2D5A3D",
      primaryLight: "#E8F2EC",
      primaryDark: "#1A3D28",
      bgPage: "bg-[#F2F8F4]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#E8F2EC]",
      bgDark: "bg-[#0F2018]",
      textDark: "text-[#0A1A10]",
      textMuted: "text-[#4A7058]",
      textAccent: "text-[#2D5A3D]",
      borderAccent: "border-[#B0CDB8]",
      gradientFrom: "#E8F2EC",
      gradientTo: "#D5E8DC",
      shadowColor: "rgba(45,90,61,0.15)"
    },
    {
      slug: "moss",
      name: "Moss",
      primaryHex: "#4A6741",
      primaryLight: "#EBF2E8",
      primaryDark: "#2D4428",
      bgPage: "bg-[#F4F8F2]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#EBF2E8]",
      bgDark: "bg-[#1C2E19]",
      textDark: "text-[#142210]",
      textMuted: "text-[#587050]",
      textAccent: "text-[#4A6741]",
      borderAccent: "border-[#B8CEB0]",
      gradientFrom: "#EBF2E8",
      gradientTo: "#D8E8D4",
      shadowColor: "rgba(74,103,65,0.15)"
    },
    {
      slug: "emerald",
      name: "Emerald",
      primaryHex: "#1B6B3A",
      primaryLight: "#E5F4EC",
      primaryDark: "#0F4525",
      bgPage: "bg-[#F0FAF4]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#E5F4EC]",
      bgDark: "bg-[#082818]",
      textDark: "text-[#051C10]",
      textMuted: "text-[#3D7850]",
      textAccent: "text-[#1B6B3A]",
      borderAccent: "border-[#A8D4B8]",
      gradientFrom: "#E5F4EC",
      gradientTo: "#CCEAD8",
      shadowColor: "rgba(27,107,58,0.15)"
    },
  ],
  // nat-bamboo
  "nat-bamboo": [
    {
      slug: "bamboo",
      name: "Bamboo",
      primaryHex: "#8B956D",
      primaryLight: "#F2F3EB",
      primaryDark: "#5F6A40",
      bgPage: "bg-[#F8F9F3]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F2F3EB]",
      bgDark: "bg-[#333A24]",
      textDark: "text-[#21260F]",
      textMuted: "text-[#727A56]",
      textAccent: "text-[#8B956D]",
      borderAccent: "border-[#CCCFA8]",
      gradientFrom: "#F2F3EB",
      gradientTo: "#E4E7D6",
      shadowColor: "rgba(139,149,109,0.15)"
    },
    {
      slug: "sage-nat",
      name: "Sage",
      primaryHex: "#7D9B76",
      primaryLight: "#EFF4EE",
      primaryDark: "#4A6741",
      bgPage: "bg-[#F7FAF6]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#EFF4EE]",
      bgDark: "bg-[#2D3D2A]",
      textDark: "text-[#1C2B1A]",
      textMuted: "text-[#6B826A]",
      textAccent: "text-[#7D9B76]",
      borderAccent: "border-[#C8D9C4]",
      gradientFrom: "#EFF4EE",
      gradientTo: "#DDE9DA",
      shadowColor: "rgba(125,155,118,0.15)"
    },
    {
      slug: "warm-olive",
      name: "Warm Olive",
      primaryHex: "#7A8B5A",
      primaryLight: "#EFF2E5",
      primaryDark: "#506038",
      bgPage: "bg-[#F6F8F0]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#EFF2E5]",
      bgDark: "bg-[#2E3520]",
      textDark: "text-[#1E2412]",
      textMuted: "text-[#6A7850]",
      textAccent: "text-[#7A8B5A]",
      borderAccent: "border-[#C5CCA8]",
      gradientFrom: "#EFF2E5",
      gradientTo: "#E2E8D2",
      shadowColor: "rgba(122,139,90,0.15)"
    },
  ],
  // nat-sunset
  "nat-sunset": [
    {
      slug: "terracotta-nat",
      name: "Terracotta",
      primaryHex: "#C4784A",
      primaryLight: "#FDF0E8",
      primaryDark: "#9B5025",
      bgPage: "bg-[#FEF8F3]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FDF0E8]",
      bgDark: "bg-[#3D1E10]",
      textDark: "text-[#2C1408]",
      textMuted: "text-[#9B6848]",
      textAccent: "text-[#C4784A]",
      borderAccent: "border-[#EDD0B8]",
      gradientFrom: "#FDF0E8",
      gradientTo: "#F5E2D0",
      shadowColor: "rgba(196,120,74,0.15)"
    },
    {
      slug: "amber",
      name: "Amber",
      primaryHex: "#C49A3A",
      primaryLight: "#FCF5E0",
      primaryDark: "#9A7010",
      bgPage: "bg-[#FEFBF2]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FCF5E0]",
      bgDark: "bg-[#3A2C08]",
      textDark: "text-[#281E04]",
      textMuted: "text-[#9A8040]",
      textAccent: "text-[#C49A3A]",
      borderAccent: "border-[#ECD8A0]",
      gradientFrom: "#FCF5E0",
      gradientTo: "#F5EACC",
      shadowColor: "rgba(196,154,58,0.15)"
    },
    {
      slug: "burnt-orange",
      name: "Burnt Orange",
      primaryHex: "#C4602A",
      primaryLight: "#FDEEE5",
      primaryDark: "#9B3C08",
      bgPage: "bg-[#FEF6F0]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FDEEE5]",
      bgDark: "bg-[#3D1808]",
      textDark: "text-[#2C1004]",
      textMuted: "text-[#9B5830]",
      textAccent: "text-[#C4602A]",
      borderAccent: "border-[#EDCAB0]",
      gradientFrom: "#FDEEE5",
      gradientTo: "#F5DECE",
      shadowColor: "rgba(196,96,42,0.15)"
    },
  ],
  // nat-ocean
  "nat-ocean": [
    {
      slug: "teal",
      name: "Teal",
      primaryHex: "#2D7D8A",
      primaryLight: "#E5F4F6",
      primaryDark: "#1A5560",
      bgPage: "bg-[#F0F9FA]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#E5F4F6]",
      bgDark: "bg-[#0F2E33]",
      textDark: "text-[#082025]",
      textMuted: "text-[#407880]",
      textAccent: "text-[#2D7D8A]",
      borderAccent: "border-[#A8D4D8]",
      gradientFrom: "#E5F4F6",
      gradientTo: "#CCEAEE",
      shadowColor: "rgba(45,125,138,0.15)"
    },
    {
      slug: "ocean-blue",
      name: "Ocean Blue",
      primaryHex: "#1E5C8A",
      primaryLight: "#E5EEF8",
      primaryDark: "#0F3A60",
      bgPage: "bg-[#F0F6FC]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#E5EEF8]",
      bgDark: "bg-[#081C30]",
      textDark: "text-[#051422]",
      textMuted: "text-[#3A6080]",
      textAccent: "text-[#1E5C8A]",
      borderAccent: "border-[#A8C4D8]",
      gradientFrom: "#E5EEF8",
      gradientTo: "#CCE0F0",
      shadowColor: "rgba(30,92,138,0.15)"
    },
    {
      slug: "seafoam",
      name: "Seafoam",
      primaryHex: "#4A9B8A",
      primaryLight: "#E8F5F2",
      primaryDark: "#2D7060",
      bgPage: "bg-[#F2FAF8]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#E8F5F2]",
      bgDark: "bg-[#182E28]",
      textDark: "text-[#10201C]",
      textMuted: "text-[#508878]",
      textAccent: "text-[#4A9B8A]",
      borderAccent: "border-[#B0D8D0]",
      gradientFrom: "#E8F5F2",
      gradientTo: "#D0ECE8",
      shadowColor: "rgba(74,155,138,0.15)"
    },
  ],
  // nat-stone
  "nat-stone": [
    {
      slug: "warm-gray",
      name: "Warm Gray",
      primaryHex: "#8B7D6B",
      primaryLight: "#F3F0EC",
      primaryDark: "#605044",
      bgPage: "bg-[#F8F5F2]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F3F0EC]",
      bgDark: "bg-[#302820]",
      textDark: "text-[#201C16]",
      textMuted: "text-[#786860]",
      textAccent: "text-[#8B7D6B]",
      borderAccent: "border-[#D4CAC0]",
      gradientFrom: "#F3F0EC",
      gradientTo: "#E8E2DA",
      shadowColor: "rgba(139,125,107,0.15)"
    },
    {
      slug: "taupe",
      name: "Taupe",
      primaryHex: "#9B8B7A",
      primaryLight: "#F4F1ED",
      primaryDark: "#705A48",
      bgPage: "bg-[#FAF7F4]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F4F1ED]",
      bgDark: "bg-[#38301E]",
      textDark: "text-[#281C10]",
      textMuted: "text-[#807060]",
      textAccent: "text-[#9B8B7A]",
      borderAccent: "border-[#D8CEBE]",
      gradientFrom: "#F4F1ED",
      gradientTo: "#EAE4D8",
      shadowColor: "rgba(155,139,122,0.15)"
    },
    {
      slug: "sand",
      name: "Sand",
      primaryHex: "#C4B49A",
      primaryLight: "#FAF6F0",
      primaryDark: "#9A8870",
      bgPage: "bg-[#FDFAF6]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FAF6F0]",
      bgDark: "bg-[#3A3020]",
      textDark: "text-[#282010]",
      textMuted: "text-[#9A8870]",
      textAccent: "text-[#B0A080]",
      borderAccent: "border-[#E4D8C8]",
      gradientFrom: "#FAF6F0",
      gradientTo: "#F2ECE0",
      shadowColor: "rgba(196,180,154,0.15)"
    },
  ],
  // fai-aurora
  "fai-aurora": [
    {
      slug: "lilac",
      name: "Lilac",
      primaryHex: "#9B8FCC",
      primaryLight: "#F2F0FA",
      primaryDark: "#6B60A8",
      bgPage: "bg-[#F8F6FD]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F2F0FA]",
      bgDark: "bg-[#221C48]",
      textDark: "text-[#181438]",
      textMuted: "text-[#706898]",
      textAccent: "text-[#8070B8]",
      borderAccent: "border-[#D5CFE8]",
      gradientFrom: "#F2F0FA",
      gradientTo: "#E5E0F5",
      shadowColor: "rgba(155,143,204,0.15)"
    },
    {
      slug: "periwinkle",
      name: "Periwinkle",
      primaryHex: "#8B9FCC",
      primaryLight: "#EEF2FA",
      primaryDark: "#5060A0",
      bgPage: "bg-[#F5F7FD]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#EEF2FA]",
      bgDark: "bg-[#1C2248]",
      textDark: "text-[#121838]",
      textMuted: "text-[#606890]",
      textAccent: "text-[#6070B0]",
      borderAccent: "border-[#C8D0E8]",
      gradientFrom: "#EEF2FA",
      gradientTo: "#DDE5F5",
      shadowColor: "rgba(139,159,204,0.15)"
    },
    {
      slug: "soft-purple",
      name: "Soft Purple",
      primaryHex: "#7B6FAC",
      primaryLight: "#F0EEFA",
      primaryDark: "#504088",
      bgPage: "bg-[#F7F5FD]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F0EEFA]",
      bgDark: "bg-[#1E1840]",
      textDark: "text-[#141030]",
      textMuted: "text-[#685880]",
      textAccent: "text-[#7060A0]",
      borderAccent: "border-[#CCC8E5]",
      gradientFrom: "#F0EEFA",
      gradientTo: "#E3DEF5",
      shadowColor: "rgba(123,111,172,0.15)"
    },
  ],
  // fai-starlight
  "fai-starlight": [
    {
      slug: "midnight-blue",
      name: "Midnight Blue",
      primaryHex: "#1E2D5A",
      primaryLight: "#E8EBF5",
      primaryDark: "#0F1838",
      bgPage: "bg-[#F2F4FB]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#E8EBF5]",
      bgDark: "bg-[#070C20]",
      textDark: "text-[#050A18]",
      textMuted: "text-[#404878]",
      textAccent: "text-[#3050A0]",
      borderAccent: "border-[#B0B8D8]",
      gradientFrom: "#E8EBF5",
      gradientTo: "#D5DAEE",
      shadowColor: "rgba(30,45,90,0.15)"
    },
    {
      slug: "navy-star",
      name: "Navy",
      primaryHex: "#1E3A5F",
      primaryLight: "#EEF2FA",
      primaryDark: "#0F2040",
      bgPage: "bg-[#F3F6FC]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#EEF2FA]",
      bgDark: "bg-[#081428]",
      textDark: "text-[#05101E]",
      textMuted: "text-[#405870]",
      textAccent: "text-[#2050A0]",
      borderAccent: "border-[#B0C0D8]",
      gradientFrom: "#EEF2FA",
      gradientTo: "#DCEAF5",
      shadowColor: "rgba(30,58,95,0.15)"
    },
    {
      slug: "indigo",
      name: "Indigo",
      primaryHex: "#2D2D8A",
      primaryLight: "#EBEBFA",
      primaryDark: "#181868",
      bgPage: "bg-[#F4F4FC]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#EBEBFA]",
      bgDark: "bg-[#0C0C38]",
      textDark: "text-[#080828]",
      textMuted: "text-[#484880]",
      textAccent: "text-[#3838A0]",
      borderAccent: "border-[#B8B8E0]",
      gradientFrom: "#EBEBFA",
      gradientTo: "#D8D8F5",
      shadowColor: "rgba(45,45,138,0.15)"
    },
  ],
  // fai-crystal
  "fai-crystal": [
    {
      slug: "ice-blue",
      name: "Ice Blue",
      primaryHex: "#8BB8CC",
      primaryLight: "#EBF4F8",
      primaryDark: "#5088A0",
      bgPage: "bg-[#F3F9FC]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#EBF4F8]",
      bgDark: "bg-[#1C3848]",
      textDark: "text-[#102030]",
      textMuted: "text-[#5880A0]",
      textAccent: "text-[#6098B8]",
      borderAccent: "border-[#C0D8E8]",
      gradientFrom: "#EBF4F8",
      gradientTo: "#D8ECF5",
      shadowColor: "rgba(139,184,204,0.15)"
    },
    {
      slug: "silver-pearl",
      name: "Silver Pearl",
      primaryHex: "#B8C4CC",
      primaryLight: "#F0F3F5",
      primaryDark: "#8090A0",
      bgPage: "bg-[#F6F8FA]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F0F3F5]",
      bgDark: "bg-[#283038]",
      textDark: "text-[#1C2430]",
      textMuted: "text-[#7080A0]",
      textAccent: "text-[#8090A8]",
      borderAccent: "border-[#D0D8E0]",
      gradientFrom: "#F0F3F5",
      gradientTo: "#E5EAEE",
      shadowColor: "rgba(184,196,204,0.15)"
    },
    {
      slug: "pearl-white",
      name: "Pearl White",
      primaryHex: "#D4D8DC",
      primaryLight: "#F8F9FA",
      primaryDark: "#A0A8B0",
      bgPage: "bg-[#FAFBFC]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F8F9FA]",
      bgDark: "bg-[#303840]",
      textDark: "text-[#202830]",
      textMuted: "text-[#8090A0]",
      textAccent: "text-[#9098A8]",
      borderAccent: "border-[#E0E4E8]",
      gradientFrom: "#F8F9FA",
      gradientTo: "#EEF0F3",
      shadowColor: "rgba(212,216,220,0.15)"
    },
  ],
  // fai-enchanted
  "fai-enchanted": [
    {
      slug: "dusty-rose-fai",
      name: "Dusty Rose",
      primaryHex: "#C4837A",
      primaryLight: "#FCF0EE",
      primaryDark: "#9B5A52",
      bgPage: "bg-[#FEF8F7]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FCF0EE]",
      bgDark: "bg-[#3D2825]",
      textDark: "text-[#2C1E1C]",
      textMuted: "text-[#9B7570]",
      textAccent: "text-[#C4837A]",
      borderAccent: "border-[#EDD5D0]",
      gradientFrom: "#FCF0EE",
      gradientTo: "#F5E0DB",
      shadowColor: "rgba(196,131,122,0.15)"
    },
    {
      slug: "antique-gold",
      name: "Antique Gold",
      primaryHex: "#C9A96E",
      primaryLight: "#FBF5E6",
      primaryDark: "#9A7838",
      bgPage: "bg-[#FEFAF2]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FBF5E6]",
      bgDark: "bg-[#382A10]",
      textDark: "text-[#261C08]",
      textMuted: "text-[#887050]",
      textAccent: "text-[#C9A96E]",
      borderAccent: "border-[#E8D5A0]",
      gradientFrom: "#FBF5E6",
      gradientTo: "#F5EACC",
      shadowColor: "rgba(201,169,110,0.15)"
    },
    {
      slug: "ivory-dream",
      name: "Ivory Dream",
      primaryHex: "#D4C4A0",
      primaryLight: "#FBF8F0",
      primaryDark: "#A89060",
      bgPage: "bg-[#FEFCF6]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FBF8F0]",
      bgDark: "bg-[#3A3020]",
      textDark: "text-[#282010]",
      textMuted: "text-[#8A7A60]",
      textAccent: "text-[#B89A60]",
      borderAccent: "border-[#EDE0C0]",
      gradientFrom: "#FBF8F0",
      gradientTo: "#F5EDD8",
      shadowColor: "rgba(212,196,160,0.15)"
    },
  ],
  // fai-dreamy
  "fai-dreamy": [
    {
      slug: "soft-lavender",
      name: "Soft Lavender",
      primaryHex: "#B8A4C8",
      primaryLight: "#F6F0FA",
      primaryDark: "#8870A0",
      bgPage: "bg-[#FAF6FD]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F6F0FA]",
      bgDark: "bg-[#2A1F38]",
      textDark: "text-[#1E1528]",
      textMuted: "text-[#806890]",
      textAccent: "text-[#9878B0]",
      borderAccent: "border-[#DCCCEA]",
      gradientFrom: "#F6F0FA",
      gradientTo: "#EADDF5",
      shadowColor: "rgba(184,164,200,0.15)"
    },
    {
      slug: "baby-pink",
      name: "Baby Pink",
      primaryHex: "#E8A4B8",
      primaryLight: "#FEF0F4",
      primaryDark: "#C47090",
      bgPage: "bg-[#FFF5F8]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FEF0F4]",
      bgDark: "bg-[#3D1F28]",
      textDark: "text-[#2C1520]",
      textMuted: "text-[#9B7080]",
      textAccent: "text-[#C47090]",
      borderAccent: "border-[#F0D0DC]",
      gradientFrom: "#FEF0F4",
      gradientTo: "#F8DCEA",
      shadowColor: "rgba(232,164,184,0.15)"
    },
    {
      slug: "mint-dream",
      name: "Mint Dream",
      primaryHex: "#A4C8B8",
      primaryLight: "#EEF7F3",
      primaryDark: "#609880",
      bgPage: "bg-[#F5FBF8]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#EEF7F3]",
      bgDark: "bg-[#1E3830]",
      textDark: "text-[#142820]",
      textMuted: "text-[#608878]",
      textAccent: "text-[#6AA890]",
      borderAccent: "border-[#C8E0D8]",
      gradientFrom: "#EEF7F3",
      gradientTo: "#DCEFE8",
      shadowColor: "rgba(164,200,184,0.15)"
    },
  ],
  // adt-javanese
  "adt-javanese": [
    {
      slug: "deep-maroon",
      name: "Deep Maroon",
      primaryHex: "#6B1D2A",
      primaryLight: "#F5E8EA",
      primaryDark: "#450F18",
      bgPage: "bg-[#FDF5F6]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F5E8EA]",
      bgDark: "bg-[#200810]",
      textDark: "text-[#180608]",
      textMuted: "text-[#7A5058]",
      textAccent: "text-[#6B1D2A]",
      borderAccent: "border-[#D8B0B8]",
      gradientFrom: "#F5E8EA",
      gradientTo: "#EDD0D5",
      shadowColor: "rgba(107,29,42,0.15)",
      secondaryHex: "#C9A96E"
    },
    {
      slug: "royal-gold",
      name: "Royal Gold",
      primaryHex: "#C9A96E",
      primaryLight: "#FBF5E6",
      primaryDark: "#9A7838",
      bgPage: "bg-[#1C1008]",
      bgSection1: "bg-[#241808]",
      bgSection2: "bg-[#1C1008]",
      bgDark: "bg-[#100800]",
      textDark: "text-[#F5EDD8]",
      textMuted: "text-[#C8A870]",
      textAccent: "text-[#C9A96E]",
      borderAccent: "border-[#6B4020]",
      gradientFrom: "#241808",
      gradientTo: "#1C1008",
      shadowColor: "rgba(201,169,110,0.20)",
      secondaryHex: "#6B1D2A"
    },
    {
      slug: "dark-brown",
      name: "Dark Brown",
      primaryHex: "#8B5A2B",
      primaryLight: "#F5EDE0",
      primaryDark: "#5A3010",
      bgPage: "bg-[#FDF8F2]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F5EDE0]",
      bgDark: "bg-[#2A1808]",
      textDark: "text-[#201008]",
      textMuted: "text-[#806040]",
      textAccent: "text-[#8B5A2B]",
      borderAccent: "border-[#D8C0A0]",
      gradientFrom: "#F5EDE0",
      gradientTo: "#EEDAD0",
      shadowColor: "rgba(139,90,43,0.15)",
      secondaryHex: "#C9A96E"
    },
  ],
  // adt-sundanese
  "adt-sundanese": [
    {
      slug: "royal-blue",
      name: "Royal Blue",
      primaryHex: "#1E3A5F",
      primaryLight: "#E8EFF8",
      primaryDark: "#0F2040",
      bgPage: "bg-[#F2F6FC]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#E8EFF8]",
      bgDark: "bg-[#080F20]",
      textDark: "text-[#050B18]",
      textMuted: "text-[#3A5878]",
      textAccent: "text-[#1E3A5F]",
      borderAccent: "border-[#A8C0D8]",
      gradientFrom: "#E8EFF8",
      gradientTo: "#D5E2F2",
      shadowColor: "rgba(30,58,95,0.15)",
      secondaryHex: "#C9A96E"
    },
    {
      slug: "navy-deep",
      name: "Navy Deep",
      primaryHex: "#0F2040",
      primaryLight: "#E5ECF5",
      primaryDark: "#060F20",
      bgPage: "bg-[#EFF4FB]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#E5ECF5]",
      bgDark: "bg-[#040810]",
      textDark: "text-[#030608]",
      textMuted: "text-[#304860]",
      textAccent: "text-[#0F2040]",
      borderAccent: "border-[#A0B5CC]",
      gradientFrom: "#E5ECF5",
      gradientTo: "#CCDBEE",
      shadowColor: "rgba(15,32,64,0.15)",
      secondaryHex: "#C9A96E"
    },
    {
      slug: "cobalt",
      name: "Cobalt",
      primaryHex: "#1A3A8A",
      primaryLight: "#E8EEF8",
      primaryDark: "#0F2060",
      bgPage: "bg-[#F2F5FC]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#E8EEF8]",
      bgDark: "bg-[#080E28]",
      textDark: "text-[#050820]",
      textMuted: "text-[#384880]",
      textAccent: "text-[#1A3A8A]",
      borderAccent: "border-[#A8B5D8]",
      gradientFrom: "#E8EEF8",
      gradientTo: "#D5DCEE",
      shadowColor: "rgba(26,58,138,0.15)",
      secondaryHex: "#C9A96E"
    },
  ],
  // adt-batak
  "adt-batak": [
    {
      slug: "deep-red",
      name: "Deep Red",
      primaryHex: "#8B1A1A",
      primaryLight: "#F8E8E8",
      primaryDark: "#5A0808",
      bgPage: "bg-[#FDF4F4]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F8E8E8]",
      bgDark: "bg-[#200505]",
      textDark: "text-[#180404]",
      textMuted: "text-[#7A4848]",
      textAccent: "text-[#8B1A1A]",
      borderAccent: "border-[#D8A8A8]",
      gradientFrom: "#F8E8E8",
      gradientTo: "#F0D0D0",
      shadowColor: "rgba(139,26,26,0.15)",
      secondaryHex: "#C9A96E"
    },
    {
      slug: "black-gold",
      name: "Black Gold",
      primaryHex: "#C9A96E",
      primaryLight: "#FBF5E6",
      primaryDark: "#9A7838",
      bgPage: "bg-[#141410]",
      bgSection1: "bg-[#1C1C18]",
      bgSection2: "bg-[#141410]",
      bgDark: "bg-[#080808]",
      textDark: "text-[#F5EDD8]",
      textMuted: "text-[#C8A870]",
      textAccent: "text-[#C9A96E]",
      borderAccent: "border-[#504020]",
      gradientFrom: "#1C1C18",
      gradientTo: "#141410",
      shadowColor: "rgba(201,169,110,0.20)",
      secondaryHex: "#8B1A1A"
    },
    {
      slug: "warm-maroon",
      name: "Warm Maroon",
      primaryHex: "#7A1F1F",
      primaryLight: "#F6EAEA",
      primaryDark: "#4A0E0E",
      bgPage: "bg-[#FDF5F5]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F6EAEA]",
      bgDark: "bg-[#1E0808]",
      textDark: "text-[#160506]",
      textMuted: "text-[#724545]",
      textAccent: "text-[#7A1F1F]",
      borderAccent: "border-[#D5AAAA]",
      gradientFrom: "#F6EAEA",
      gradientTo: "#EDD5D5",
      shadowColor: "rgba(122,31,31,0.15)",
      secondaryHex: "#C9A96E"
    },
  ],
  // adt-minang
  "adt-minang": [
    {
      slug: "deep-purple",
      name: "Deep Purple",
      primaryHex: "#4A1A6B",
      primaryLight: "#F0E8F8",
      primaryDark: "#2D0845",
      bgPage: "bg-[#F8F2FD]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F0E8F8]",
      bgDark: "bg-[#150520]",
      textDark: "text-[#100318]",
      textMuted: "text-[#684880]",
      textAccent: "text-[#4A1A6B]",
      borderAccent: "border-[#CCB0E0]",
      gradientFrom: "#F0E8F8",
      gradientTo: "#E3D5F2",
      shadowColor: "rgba(74,26,107,0.15)",
      secondaryHex: "#C9A96E"
    },
    {
      slug: "indigo-royal",
      name: "Indigo Royal",
      primaryHex: "#2D1A8A",
      primaryLight: "#ECEAFA",
      primaryDark: "#1A0860",
      bgPage: "bg-[#F5F3FD]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#ECEAFA]",
      bgDark: "bg-[#0C0828]",
      textDark: "text-[#080520]",
      textMuted: "text-[#484880]",
      textAccent: "text-[#2D1A8A]",
      borderAccent: "border-[#BCB5E0]",
      gradientFrom: "#ECEAFA",
      gradientTo: "#DDD8F5",
      shadowColor: "rgba(45,26,138,0.15)",
      secondaryHex: "#C9A96E"
    },
    {
      slug: "royal-violet",
      name: "Royal Violet",
      primaryHex: "#5C2D8A",
      primaryLight: "#F2EAF8",
      primaryDark: "#380F60",
      bgPage: "bg-[#FAF4FD]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#F2EAF8]",
      bgDark: "bg-[#180828]",
      textDark: "text-[#110520]",
      textMuted: "text-[#6A4880]",
      textAccent: "text-[#5C2D8A]",
      borderAccent: "border-[#CCB8E0]",
      gradientFrom: "#F2EAF8",
      gradientTo: "#E5D5F2",
      shadowColor: "rgba(92,45,138,0.15)",
      secondaryHex: "#C9A96E"
    },
  ],
  // adt-betawi
  "adt-betawi": [
    {
      slug: "coral-red",
      name: "Coral Red",
      primaryHex: "#C4504A",
      primaryLight: "#FDECEA",
      primaryDark: "#9B2820",
      bgPage: "bg-[#FEF6F5]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FDECEA]",
      bgDark: "bg-[#3D1412]",
      textDark: "text-[#2C0E0C]",
      textMuted: "text-[#9B5550]",
      textAccent: "text-[#C4504A]",
      borderAccent: "border-[#EEC8C5]",
      gradientFrom: "#FDECEA",
      gradientTo: "#F8D8D5",
      shadowColor: "rgba(196,80,74,0.15)",
      secondaryHex: "#C9A96E"
    },
    {
      slug: "festival-gold",
      name: "Festival Gold",
      primaryHex: "#C9A96E",
      primaryLight: "#FBF5E6",
      primaryDark: "#9A7838",
      bgPage: "bg-[#FEFAF2]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FBF5E6]",
      bgDark: "bg-[#382A10]",
      textDark: "text-[#261C08]",
      textMuted: "text-[#887050]",
      textAccent: "text-[#C9A96E]",
      borderAccent: "border-[#E8D5A0]",
      gradientFrom: "#FBF5E6",
      gradientTo: "#F5EACC",
      shadowColor: "rgba(201,169,110,0.15)",
      secondaryHex: "#C4504A"
    },
    {
      slug: "warm-orange",
      name: "Warm Orange",
      primaryHex: "#C4784A",
      primaryLight: "#FDF0E8",
      primaryDark: "#9B5025",
      bgPage: "bg-[#FEF8F3]",
      bgSection1: "bg-white",
      bgSection2: "bg-[#FDF0E8]",
      bgDark: "bg-[#3D1E10]",
      textDark: "text-[#2C1408]",
      textMuted: "text-[#9B6848]",
      textAccent: "text-[#C4784A]",
      borderAccent: "border-[#EDD0B8]",
      gradientFrom: "#FDF0E8",
      gradientTo: "#F5E2D0",
      shadowColor: "rgba(196,120,74,0.15)",
      secondaryHex: "#C9A96E"
    },
  ],
}

export function getPalette(templateSlug: string, paletteSlug: string): ColorPalette | undefined {
  return templatePalettes[templateSlug]?.find(p => p.slug === paletteSlug)
}

export function getTemplatePalettes(templateSlug: string): ColorPalette[] {
  return templatePalettes[templateSlug] ?? []
}

export function getDefaultPalette(templateSlug: string): ColorPalette | undefined {
  return templatePalettes[templateSlug]?.[0]
}