#!/usr/bin/env python3
"""
Generate the Wedding Invitation Deployment Guide PDF.
Uses fpdf2 with DejaVuSans fonts (full Unicode support).
"""

from fpdf import FPDF
import os

# ── Fonts ──────────────────────────────────────────────────
FONT_DIR = "/usr/share/fonts/truetype/dejavu"
REGULAR   = os.path.join(FONT_DIR, "DejaVuSans.ttf")
BOLD      = os.path.join(FONT_DIR, "DejaVuSans-Bold.ttf")
ITALIC    = os.path.join(FONT_DIR, "DejaVuSans-Oblique.ttf")
BOLD_IT   = os.path.join(FONT_DIR, "DejaVuSans-BoldOblique.ttf")
MONO      = os.path.join(FONT_DIR, "DejaVuSansMono.ttf")
MONO_BOLD = os.path.join(FONT_DIR, "DejaVuSansMono-Bold.ttf")

# ── Colors ─────────────────────────────────────────────────
C_PRIMARY   = (139, 69, 19)     # Saddle brown — wedding theme
C_ACCENT    = (205, 133, 63)    # Peru / warm accent
C_DARK      = (51, 51, 51)      # Body text
C_LIGHT_BG  = (250, 245, 238)   # Cream background
C_CODE_BG   = (245, 240, 233)   # Slightly darker cream for code
C_TABLE_HDR = (139, 69, 19)     # Header row
C_TABLE_ROW = (250, 245, 238)   # Alt row
C_TABLE_ALT = (255, 250, 243)   # Alt row 2
C_BORDER    = (200, 180, 160)   # Soft border
C_GREEN     = (34, 139, 34)
C_RED       = (178, 34, 34)
C_BLUE      = (30, 90, 160)

class DeploymentPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=25)
        self.set_margins(20, 25, 20)
        self.add_font("DejaVu", "", REGULAR)
        self.add_font("DejaVu", "B", BOLD)
        self.add_font("DejaVu", "I", ITALIC)
        self.add_font("DejaVu", "BI", BOLD_IT)
        self.add_font("Mono", "", MONO)
        self.add_font("Mono", "B", MONO_BOLD)

    def header(self):
        """Page header — skip on cover page."""
        if self.page_no() == 1:
            return
        self.set_font("DejaVu", "I", 8)
        self.set_text_color(*C_BORDER)
        self.cell(0, 8, "Wedding Invitation — Deployment Guide", align="L")
        self.cell(0, 8, f"Page {self.page_no() - 1}", align="R", new_x="RIGHT", new_y="NEXT")
        self.set_draw_color(*C_BORDER)
        self.line(20, 23, 190, 23)
        self.ln(5)

    def footer(self):
        """Page footer."""
        if self.page_no() == 1:
            return
        self.set_y(-18)
        self.set_font("DejaVu", "I", 7)
        self.set_text_color(*C_BORDER)
        self.cell(0, 5, "Generated by Hermes Agent — June 2026", align="C")

    # ── Helpers ────────────────────────────────────────────

    def section_title(self, num, title):
        """Major section title with colored bar."""
        self.ln(4)
        self.set_fill_color(*C_PRIMARY)
        self.set_text_color(255, 255, 255)
        self.set_font("DejaVu", "B", 13)
        self.cell(0, 9, f"  {num}. {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(4)
        self.set_text_color(*C_DARK)

    def subsection_title(self, title):
        """Subsection heading."""
        self.ln(2)
        self.set_font("DejaVu", "B", 11)
        self.set_text_color(*C_PRIMARY)
        self.cell(0, 7, title, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*C_DARK)
        self.ln(1)

    def body_text(self, text):
        """Regular paragraph text."""
        self.set_font("DejaVu", "", 10)
        self.set_text_color(*C_DARK)
        self.multi_cell(0, 6, text)
        self.ln(2)

    def body_text_html(self, segments):
        """Write text with mixed formatting. segments = [(text, style), ...]
        style: '' normal, 'B' bold, 'I' italic, 'BI' bold-italic"""
        self.set_text_color(*C_DARK)
        for text, style in segments:
            self.set_font("DejaVu", style, 10)
            self.write(6, text)

    def bullet(self, text, indent=0):
        """Bullet point."""
        x = 20 + indent
        self.set_x(x)
        self.set_font("DejaVu", "", 10)
        self.set_text_color(*C_ACCENT)
        self.cell(5, 6, "->", new_x="RIGHT")
        self.set_text_color(*C_DARK)
        self.multi_cell(0, 6, text)
        self.ln(0.5)

    def numbered(self, num, text, indent=0):
        """Numbered list item."""
        x = 20 + indent
        self.set_x(x)
        self.set_font("DejaVu", "B", 10)
        self.set_text_color(*C_PRIMARY)
        self.cell(7, 6, f"{num}.", new_x="RIGHT")
        self.set_font("DejaVu", "", 10)
        self.set_text_color(*C_DARK)
        self.multi_cell(0, 6, text)
        self.ln(0.5)

    def code_block(self, code):
        """Monospace code block with background."""
        self.ln(1)
        # Calculate height
        lines = code.strip().split("\n")
        line_h = 5
        total_h = len(lines) * line_h + 4

        # Check if we need a page break
        if self.get_y() + total_h > self.h - 25:
            self.add_page()

        x = self.get_x()
        y = self.get_y()

        # Background
        self.set_fill_color(*C_CODE_BG)
        self.set_draw_color(*C_BORDER)
        # Use rect for background
        self.rect(x, y, 170, total_h, style="DF")

        # Code text
        self.set_xy(x + 3, y + 2)
        self.set_font("Mono", "", 8.5)
        self.set_text_color(60, 60, 60)
        for line in lines:
            self.set_x(x + 3)
            self.cell(0, line_h, line, new_x="LMARGIN", new_y="NEXT")

        self.ln(3)
        self.set_text_color(*C_DARK)

    def info_box(self, text, box_type="info"):
        """Colored callout box. box_type: info, warning, danger, success"""
        colors = {
            "info":    (230, 240, 250),
            "warning": (255, 248, 220),
            "danger":  (255, 235, 230),
            "success": (230, 245, 230),
        }
        borders = {
            "info":    (30, 90, 160),
            "warning": (200, 150, 0),
            "danger":  (178, 34, 34),
            "success": (34, 139, 34),
        }
        bg = colors.get(box_type, colors["info"])
        bd = borders.get(box_type, borders["info"])

        self.ln(1)
        lines = text.split("\n")
        total_h = len(lines) * 6 + 6

        if self.get_y() + total_h > self.h - 25:
            self.add_page()

        x = self.get_x()
        y = self.get_y()

        # Background bar on left
        self.set_fill_color(*bd)
        self.rect(x, y, 2, total_h, style="F")
        self.set_fill_color(*bg)
        self.rect(x + 2, y, 168, total_h, style="F")

        self.set_xy(x + 6, y + 3)
        self.set_font("DejaVu", "", 9.5)
        self.set_text_color(*C_DARK)
        for line in lines:
            self.set_x(x + 6)
            self.multi_cell(162, 6, line)
        self.ln(2)
        self.set_text_color(*C_DARK)

    def data_table(self, headers, rows, col_widths=None):
        """Simple table with header and rows."""
        if col_widths is None:
            avail = 170
            col_widths = [avail / len(headers)] * len(headers)

        # Check space
        needed = (len(rows) + 1) * 7 + 2
        if self.get_y() + needed > self.h - 25:
            self.add_page()

        # Header
        self.set_font("DejaVu", "B", 9)
        self.set_fill_color(*C_TABLE_HDR)
        self.set_text_color(255, 255, 255)
        for i, h in enumerate(headers):
            self.cell(col_widths[i], 7, h, border="1", fill=True, align="C")
        self.ln()

        # Rows
        self.set_font("DejaVu", "", 8.5)
        self.set_text_color(*C_DARK)
        for r_idx, row in enumerate(rows):
            if self.get_y() + 7 > self.h - 25:
                self.add_page()
                # Re-print header
                self.set_font("DejaVu", "B", 9)
                self.set_fill_color(*C_TABLE_HDR)
                self.set_text_color(255, 255, 255)
                for i, h in enumerate(headers):
                    self.cell(col_widths[i], 7, h, border="1", fill=True, align="C")
                self.ln()
                self.set_font("DejaVu", "", 8.5)
                self.set_text_color(*C_DARK)

            bg = C_TABLE_ALT if r_idx % 2 == 0 else C_TABLE_ROW
            self.set_fill_color(*bg)
            for i, cell in enumerate(row):
                self.cell(col_widths[i], 7, cell, border="1", fill=True)
            self.ln()

        self.ln(3)
        self.set_text_color(*C_DARK)


# ═══════════════════════════════════════════════════════════
#  BUILD THE PDF
# ═══════════════════════════════════════════════════════════

def build_pdf():
    pdf = DeploymentPDF()

    # ── COVER PAGE ─────────────────────────────────────────
    pdf.add_page()
    pdf.set_y(50)

    # Decorative top bar
    pdf.set_fill_color(*C_PRIMARY)
    pdf.rect(0, 0, 210, 5, style="F")
    pdf.set_fill_color(*C_ACCENT)
    pdf.rect(0, 5, 210, 2, style="F")

    # Title
    pdf.set_font("DejaVu", "B", 28)
    pdf.set_text_color(*C_PRIMARY)
    pdf.cell(0, 14, "Wedding Digital Invitation", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.set_font("DejaVu", "", 14)
    pdf.set_text_color(*C_ACCENT)
    pdf.cell(0, 10, "Deployment Guide", align="C", new_x="LMARGIN", new_y="NEXT")

    # Divider
    pdf.ln(5)
    pdf.set_draw_color(*C_ACCENT)
    pdf.set_line_width(0.8)
    x_center = 105
    pdf.line(x_center - 40, pdf.get_y(), x_center + 40, pdf.get_y())
    pdf.ln(8)

    # Subtitle
    pdf.set_font("DejaVu", "I", 11)
    pdf.set_text_color(*C_DARK)
    pdf.multi_cell(0, 6, "Complete guide for deploying the wedding invitation\nplatform on a fresh server instance from GitHub.", align="C")
    pdf.ln(15)

    # Tech stack box
    pdf.set_font("DejaVu", "B", 11)
    pdf.set_text_color(*C_PRIMARY)
    pdf.cell(0, 8, "Technology Stack", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    stack = [
        ("Frontend", "Next.js 14 + Tailwind CSS + Swiper"),
        ("Backend", "Node.js + Express.js"),
        ("Database", "PostgreSQL 16"),
        ("Cache", "Redis 7"),
        ("Proxy", "Nginx 1.27"),
        ("Containerization", "Docker + Docker Compose"),
    ]
    for label, value in stack:
        pdf.set_font("DejaVu", "B", 9)
        pdf.set_text_color(*C_PRIMARY)
        pdf.cell(50, 6, label, align="R", new_x="RIGHT")
        pdf.cell(5, 6, "  :  ", align="C", new_x="RIGHT")
        pdf.set_font("DejaVu", "", 9)
        pdf.set_text_color(*C_DARK)
        pdf.cell(0, 6, value, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(15)

    # Version info
    pdf.set_font("DejaVu", "", 9)
    pdf.set_text_color(*C_BORDER)
    pdf.cell(0, 5, "Version 1.0  |  June 2026", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, "Generated by Hermes Agent", align="C", new_x="LMARGIN", new_y="NEXT")

    # Bottom bar
    pdf.set_y(-15)
    pdf.set_fill_color(*C_PRIMARY)
    pdf.rect(0, pdf.get_y() - 2, 210, 5, style="F")
    pdf.set_fill_color(*C_ACCENT)
    pdf.rect(0, pdf.get_y() + 3, 210, 2, style="F")

    # ── TABLE OF CONTENTS ─────────────────────────────────
    pdf.add_page()
    pdf.set_font("DejaVu", "B", 18)
    pdf.set_text_color(*C_PRIMARY)
    pdf.cell(0, 12, "Table of Contents", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    pdf.set_draw_color(*C_ACCENT)
    pdf.set_line_width(0.5)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(5)

    toc = [
        ("1.", "Why \"Missing\" Files Aren't Actually Missing"),
        ("2.", "Architecture Overview"),
        ("3.", "Prerequisites (Fresh Instance)"),
        ("4.", "Step-by-Step Deployment"),
        ("5.", "Post-Deployment Setup"),
        ("6.", "Common Operations"),
        ("7.", "Environment Variables Reference"),
        ("8.", "Database Migrations"),
        ("9.", "Troubleshooting"),
        ("10.", "Production Checklist"),
    ]
    for num, title in toc:
        pdf.set_font("DejaVu", "B", 10)
        pdf.set_text_color(*C_PRIMARY)
        pdf.cell(12, 7, num, new_x="RIGHT")
        pdf.set_font("DejaVu", "", 10)
        pdf.set_text_color(*C_DARK)
        pdf.cell(0, 7, title, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

    # ── SECTION 1: Why Missing Files ──────────────────────
    pdf.add_page()
    pdf.section_title("1", "Why \"Missing\" Files Aren't Actually Missing")

    pdf.body_text(
        "When you push this project to GitHub, several large or sensitive items are "
        "intentionally excluded via .gitignore. Here is how they get recreated on a new instance:"
    )

    pdf.data_table(
        ["Excluded File/Folder", "Size", "How It's Recreated"],
        [
            ["frontend/node_modules/", "~360 MB", "Docker rebuild - npm install"],
            ["backend/node_modules/", "~5 MB", "Docker rebuild - npm install --production"],
            ["frontend/.next/", "~145 MB", "Docker rebuild - npm run build (standalone)"],
            [".env", "< 1 KB", "Manual - copy .env.example and fill values"],
            ["uploads/", "varies", "Docker volume - empty on first run"],
            ["postgres_data/", "varies", "Docker volume - migrations auto-run"],
        ],
        col_widths=[52, 22, 96]
    )

    pdf.subsection_title("The Key Insight")
    pdf.body_text(
        "You never need node_modules or .next on the host machine. Docker builds them "
        "inside isolated containers and discards the intermediate layers. The final images "
        "are small (~150 MB frontend, ~50 MB backend)."
    )

    pdf.code_block("""GitHub repo (source code only)
        |
        v
  docker compose up --build
        |
        |---> Frontend Dockerfile:
        |    1. npm install        <- recreates node_modules (inside container)
        |    2. npm run build      <- recreates .next/ (inside container)
        |    3. Copies only standalone output to final image
        |
        |---> Backend Dockerfile:
        |    1. npm install --production  <- recreates node_modules (inside container)
        |    2. Copies src/ to final image
        |
        |---> PostgreSQL container:
        |    1. Starts fresh with empty DB
        |    2. Runs 001_init.sql on first boot
        |    3. Backend also runs migrations on startup (idempotent)
        |
        +---> Redis container:
             1. Starts fresh with empty cache""")

    # ── SECTION 2: Architecture ───────────────────────────
    pdf.add_page()
    pdf.section_title("2", "Architecture Overview")

    pdf.code_block("""                    +----------------------------------+
                    |         Docker Network           |
                    |                                  |
   Port 8081 ----->|  Nginx (:80)                     |
                    |    |-- /     -> frontend:3000    |
                    |    |-- /api/  -> backend:4000    |
                    |    +-- /uploads/ -> backend:4000 |
                    |                                  |
                    |  Frontend (Next.js standalone)   |
                    |    +-- :3000                     |
                    |                                  |
                    |  Backend (Express.js)            |
                    |    +-- :4000                     |
                    |    |-- Postgres (:5432)          |
                    |    +-- Redis (:6379)             |
                    |                                  |
                    |  Volumes:                        |
                    |    |-- postgres_data (DB)        |
                    |    +-- uploads_data (photos)     |
                    +----------------------------------+""")

    pdf.subsection_title("Services")
    pdf.data_table(
        ["Service", "Container", "Port", "Purpose"],
        [
            ["nginx", "wedding_nginx", "8081->80", "Reverse proxy"],
            ["frontend", "wedding_frontend", "3000 (int)", "Next.js standalone server"],
            ["backend", "wedding_backend", "4000->4000", "Express.js API server"],
            ["postgres", "wedding_postgres", "5432->5432", "PostgreSQL 16 database"],
            ["redis", "wedding_redis", "6379->6379", "Redis 7 cache"],
        ],
        col_widths=[22, 35, 30, 83]
    )

    # ── SECTION 3: Prerequisites ─────────────────────────
    pdf.add_page()
    pdf.section_title("3", "Prerequisites (Fresh Instance)")

    pdf.subsection_title("3.1  Install Docker + Docker Compose")
    pdf.code_block("""# Ubuntu / Debian
curl -fsSL https://get.docker.com | sudo sh
sudo usermod -aG docker $USER
# Log out and back in for group change to take effect

# Verify
docker --version          # Docker version 24+
docker compose version    # Docker Compose v2+""")

    pdf.subsection_title("3.2  Install Git")
    pdf.code_block("sudo apt-get update && sudo apt-get install -y git")

    pdf.subsection_title("3.3  System Requirements")
    pdf.bullet("RAM: Minimum 2 GB (4 GB recommended for Next.js build)")
    pdf.bullet("Disk: 5 GB free (Docker images + volumes)")
    pdf.bullet("CPU: 1 vCPU minimum (2+ recommended for build speed)")

    # ── SECTION 4: Step-by-Step ──────────────────────────
    pdf.add_page()
    pdf.section_title("4", "Step-by-Step Deployment")

    pdf.subsection_title("Step 1 - Clone the Repository")
    pdf.code_block("""cd ~
git clone https://github.com/YOUR_USERNAME/wedding-invitation.git
cd wedding-invitation""")

    pdf.subsection_title("Step 2 - Create the Environment File")
    pdf.code_block("""# Copy the template
cp .env.example .env

# Edit with real values
nano .env""")

    pdf.info_box(
        "Critical values to change:\n"
        "- JWT_SECRET: Generate with 'openssl rand -base64 32'\n"
        "- DB_PASSWORD: Change from default 'wedding_secret'\n"
        "- BASE_URL / FRONTEND_URL: Update if using a real domain\n"
        "- NEXT_PUBLIC_API_URL: Leave empty - Nginx handles routing\n"
        "- NEXT_PUBLIC_GOOGLE_MAPS_KEY: Optional, for ceremony location map",
        "warning"
    )

    pdf.info_box("Never commit .env to Git. It is in .gitignore for security.", "danger")

    pdf.subsection_title("Step 3 - Build and Start")
    pdf.code_block("# Build all images and start containers\ndocker compose up -d --build")

    pdf.body_text(
        "What happens (takes 3-10 minutes depending on server):"
    )
    pdf.numbered(1, "Docker pulls node:20-alpine, postgres:16-alpine, redis:7-alpine, nginx:1.27-alpine")
    pdf.numbered(2, "Frontend image: npm install -> npm run build -> copies standalone output")
    pdf.numbered(3, "Backend image: npm install --production -> copies src/")
    pdf.numbered(4, "PostgreSQL starts -> runs 001_init.sql migration (creates tables)")
    pdf.numbered(5, "Redis starts")
    pdf.numbered(6, "Backend starts -> runs migrations (idempotent) -> listens on :4000")
    pdf.numbered(7, "Frontend starts -> serves Next.js standalone on :3000")
    pdf.numbered(8, "Nginx starts -> proxies traffic")

    pdf.subsection_title("Step 4 - Verify")
    pdf.code_block("""# Check all containers are running and healthy
docker compose ps

# Test the endpoints
curl http://localhost:8081/                    # Frontend (should return HTML)
curl http://localhost:8081/health              # Backend health (should return JSON)
curl http://localhost:8081/api/invitations     # API (should return JSON)""")

    pdf.body_text("Open in browser: http://YOUR_SERVER_IP:8081")

    pdf.subsection_title("Step 5 - Configure Firewall (Optional)")
    pdf.code_block("""# Open port 8081
sudo ufw allow 8081/tcp

# Or if using a custom domain with SSL (port 80/443):
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp""")

    # ── SECTION 5: Post-Deployment ───────────────────────
    pdf.add_page()
    pdf.section_title("5", "Post-Deployment Setup")

    pdf.subsection_title("5.1  Create Admin Account")
    pdf.body_text("The first user registration becomes the admin. Register at:")
    pdf.code_block("http://YOUR_SERVER_IP:8081/register")

    pdf.subsection_title("5.2  Create Your First Invitation")
    pdf.numbered(1, "Log in at /login")
    pdf.numbered(2, 'Go to Dashboard -> "Create New Invitation"')
    pdf.numbered(3, "Fill in couple names, event details, venue, etc.")
    pdf.numbered(4, "Upload bride/groom photos and gallery images")
    pdf.numbered(5, "Invitation available at http://YOUR_SERVER_IP:8081/your-slug")

    pdf.subsection_title("5.3  Upload Existing Photos (If Migrating)")
    pdf.body_text("If you have photos from a previous deployment:")
    pdf.code_block("""# Copy photos into the backend container's upload volume
docker cp ./uploads/. wedding_backend:/uploads/

# Or mount the volume and copy directly
docker run --rm -v wedding-invitation_uploads_data:/data \\
  -v $(pwd)/uploads:/src alpine cp -a /src/. /data/""")

    # ── SECTION 6: Common Operations ─────────────────────
    pdf.add_page()
    pdf.section_title("6", "Common Operations")

    pdf.subsection_title("Rebuild After Code Changes")
    pdf.code_block("""# Rebuild only the service that changed
docker compose up -d --build frontend

# Rebuild everything
docker compose up -d --build""")

    pdf.subsection_title("View Logs")
    pdf.code_block("""# All services
docker compose logs -f

# Specific service (last 50 lines, follow)
docker compose logs -f --tail 50 frontend
docker compose logs -f --tail 50 backend
docker compose logs -f --tail 50 nginx""")

    pdf.subsection_title("Restart Nginx (Fixes 502 After Container Recreate)")
    pdf.info_box(
        "When you recreate the frontend or backend container, their internal Docker IPs "
        "change. Nginx caches the old IP, causing 502 Bad Gateway. Fix: "
        "docker compose restart nginx",
        "warning"
    )
    pdf.code_block("docker compose restart nginx")

    pdf.subsection_title("Stop Everything")
    pdf.code_block("""# Containers stop but volumes (DB + uploads) are preserved
docker compose down""")

    pdf.subsection_title("Wipe Everything (Fresh Start)")
    pdf.info_box("This deletes the database AND all uploaded photos. Irreversible!", "danger")
    pdf.code_block("docker compose down -v")

    pdf.subsection_title("Backup Database")
    pdf.code_block("""# Export database to file
docker exec wedding_postgres pg_dump -U wedding wedding > backup_$(date +%Y%m%d).sql

# Restore from file
cat backup_20260101.sql | docker exec -i wedding_postgres psql -U wedding wedding""")

    pdf.subsection_title("Backup Uploaded Photos")
    pdf.code_block("""docker run --rm -v wedding-invitation_uploads_data:/data \\
  -v $(pwd):/backup alpine \\
  tar czf /backup/uploads_backup_$(date +%Y%m%d).tar.gz -C /data .""")

    # ── SECTION 7: Environment Variables ─────────────────
    pdf.add_page()
    pdf.section_title("7", "Environment Variables Reference")

    pdf.data_table(
        ["Variable", "Service", "Default", "Description"],
        [
            ["NEXT_PUBLIC_API_URL", "Frontend", "\"\" (empty)", "Backend API URL (empty=Nginx proxy)"],
            ["NEXT_PUBLIC_GOOGLE_MAPS_KEY", "Frontend", "-", "Google Maps Embed API key"],
            ["PORT", "Backend", "4000", "Backend listen port"],
            ["NODE_ENV", "Backend", "production", "Node environment"],
            ["DB_HOST", "Backend", "postgres", "PostgreSQL hostname (Docker svc)"],
            ["DB_PORT", "Backend", "5432", "PostgreSQL port"],
            ["DB_NAME", "Backend", "wedding", "Database name"],
            ["DB_USER", "Backend", "wedding", "Database user"],
            ["DB_PASSWORD", "Backend", "wedding_secret", "DB password (must match compose)"],
            ["REDIS_URL", "Backend", "redis://redis:6379", "Redis connection string"],
            ["JWT_SECRET", "Backend", "-", "Secret for JWT (generate random)"],
            ["BASE_URL", "Backend", "localhost:4000", "Backend URL for email links"],
            ["FRONTEND_URL", "Backend", "localhost:3000", "Frontend URL for CORS"],
            ["UPLOAD_DIR", "Backend", "/uploads", "Photo upload dir (in container)"],
        ],
        col_widths=[48, 18, 35, 69]
    )

    # ── SECTION 8: Database Migrations ───────────────────
    pdf.add_page()
    pdf.section_title("8", "Database Migrations")

    pdf.body_text(
        "Migrations are SQL files in backend/migrations/. They run automatically in two places:"
    )

    pdf.numbered(1, "PostgreSQL container first boot - docker-compose.yml mounts 001_init.sql "
                     "to /docker-entrypoint-initdb.d/, which PostgreSQL auto-executes on first startup only.")
    pdf.numbered(2, "Backend startup - backend/src/index.js has an initDb() function that reads all "
                     ".sql files and runs them. It catches 'already exists' errors, so it is idempotent.")

    pdf.subsection_title("Adding New Migrations")
    pdf.code_block("""# Create a new migration file (numbered sequentially)
touch backend/migrations/003_add_gift_registry.sql

# The backend will pick it up automatically on next restart.
# No manual SQL needed.""")

    # ── SECTION 9: Troubleshooting ───────────────────────
    pdf.add_page()
    pdf.section_title("9", "Troubleshooting")

    pdf.subsection_title("502 Bad Gateway")
    pdf.info_box("Cause: Nginx can't reach frontend/backend (usually after recreating a container).", "danger")
    pdf.code_block("docker compose restart nginx")

    pdf.subsection_title("Frontend Container Won't Start")
    pdf.info_box("Cause: Next.js build failed (usually out of memory).", "danger")
    pdf.code_block("""# Check logs
docker compose logs frontend

# If OOM: the Dockerfile sets NODE_OPTIONS=--max-old-space-size=3072
# Ensure the server has at least 4 GB RAM, or add swap:
sudo fallocate -l 2G /swapfile && sudo chmod 600 /swapfile
sudo mkswap /swapfile && sudo swapon /swapfile""")

    pdf.subsection_title("Database Connection Refused")
    pdf.code_block("""# Check if postgres is healthy
docker compose ps postgres

# If not healthy, check logs
docker compose logs postgres

# If DB password mismatch between .env and docker-compose.yml,
# the postgres container uses the password from docker-compose.yml.
# The backend reads from .env. They MUST match.""")

    pdf.subsection_title("Port 8081 Already in Use")
    pdf.body_text("Edit docker-compose.yml nginx service:")
    pdf.code_block("""nginx:
  ports:
    - "YOUR_PORT:80"   # e.g., "3000:80\"""")

    # ── SECTION 10: Production Checklist ─────────────────
    pdf.add_page()
    pdf.section_title("10", "Production Checklist")

    checklist = [
        ".env created with real values (especially JWT_SECRET)",
        "JWT_SECRET is a random 32+ character string (not default)",
        "DB_PASSWORD changed from default wedding_secret",
        "Firewall configured (only expose needed ports)",
        "HTTPS configured (use Nginx + Let's Encrypt or a load balancer)",
        "Database backups scheduled (cron + pg_dump)",
        "Upload backups scheduled",
        "Docker compose auto-restart on reboot (already set via restart: unless-stopped)",
        "Monitor disk space (uploads + postgres volume growth)",
    ]
    for item in checklist:
        pdf.set_font("DejaVu", "", 10)
        pdf.set_text_color(*C_ACCENT)
        pdf.cell(8, 7, "[  ]", new_x="RIGHT")
        pdf.set_text_color(*C_DARK)
        pdf.multi_cell(0, 7, item)
        pdf.ln(1)

    pdf.ln(5)
    pdf.set_draw_color(*C_ACCENT)
    pdf.set_line_width(0.5)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(5)
    pdf.set_font("DejaVu", "I", 9)
    pdf.set_text_color(*C_BORDER)
    pdf.cell(0, 5, "End of Deployment Guide - Wedding Digital Invitation v1.0", align="C")

    # ── SAVE ──────────────────────────────────────────────
    output_path = "/home/ssm-user/wedding-invitation/Wedding-Invitation-Deployment-Guide.pdf"
    pdf.output(output_path)
    print(f"PDF saved to: {output_path}")
    print(f"Total pages: {pdf.page_no()}")
    return output_path


if __name__ == "__main__":
    build_pdf()
